SOURCE = ft_error.c ft_split.c ft_utils.c ft_read_val.c ft_dict_utils.c ft_read_file.c ft_string.c main.c
NAME = rush-02

CFLAGS = -Wall -Wextra -Werror

all : ${NAME}

${NAME} : 
	cc ${CFLAGS} ${SOURCE} -o ${NAME}

fclean :
	rm -f ${NAME}
